name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  TF_VAR_vpc_cidr: "10.0.0.0/16"
  TF_VAR_public_subnet_1_cidr: "10.0.0.0/24"
  TF_VAR_public_subnet_2_cidr: "10.0.2.0/24"
  TF_VAR_availability_zone_1: "eu-west-1a"
  TF_VAR_availability_zone_2: "eu-west-1b"
  TF_VAR_public_route_cidr: "0.0.0.0/0"
  TF_VAR_public_route_table_name: "gatus-public-rt"


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::540321526518:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - run: terraform plan -input=false 
        working-directory: ./infra