name: Terraform Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  TF_VAR_vpc_cidr: "10.0.0.0/16"
  TF_VAR_public_subnet_1_cidr: "10.0.0.0/24"
  TF_VAR_public_subnet_2_cidr: "10.0.2.0/24"
  TF_VAR_availability_zone_1: "eu-west-1a"
  TF_VAR_availability_zone_2: "eu-west-1b"
  TF_VAR_container_port: "8080"
  TF_VAR_app_domain_name: "tm.khaled-projects.net"
  TF_VAR_hosted_zone_id: "Z01106103VTZ4ZOEEI6L"
  TF_VAR_http_port: "80"
  TF_VAR_https_port: "443"
  TF_VAR_ecr_repo_name: "gatus"
  TF_VAR_ecs_cluster_name: "gatus-cluster"
  TF_VAR_ecs_task_execution_role_name: "gatus-ecs-task-execution-role"
  TF_VAR_ecs_task_execution_policy_arn: "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  TF_VAR_cloudwatch_log_group_name: "/ecs/gatus"
  TF_VAR_cloudwatch_retention_days: "14"
  TF_VAR_ecs_task_family: "gatus-task"
  TF_VAR_ecs_cpu: "256"
  TF_VAR_ecs_memory: "512"
  TF_VAR_container_name: "gatus"
  TF_VAR_container_image_tag: "bc433161"
  TF_VAR_aws_region: "eu-west-1"
  TF_VAR_ecs_service_name: "gatus-service"
  TF_VAR_ecs_desired_count: "1"
  TF_VAR_ecs_launch_type: "FARGATE"
  TF_VAR_alb_name: "gatus-alb"
  TF_VAR_alb_internal: "false"
  TF_VAR_alb_type: "application"
  TF_VAR_target_group_name: "gatus-tg"
  TF_VAR_target_group_port: "8080"
  TF_VAR_target_group_protocol: "HTTP"
  TF_VAR_target_group_type: "ip"
  TF_VAR_health_check_path: "/health"
  TF_VAR_health_check_matcher: "200"
  TF_VAR_http_listener_port: "80"
  TF_VAR_http_listener_protocol: "HTTP"
  TF_VAR_redirect_port: "443"
  TF_VAR_redirect_protocol: "HTTPS"
  TF_VAR_redirect_status_code: "HTTP_301"
  TF_VAR_route53_validation_ttl: "60"
  TF_VAR_app_record_type: "A"
  TF_VAR_evaluate_target_health: "true"
  TF_VAR_acm_domain_name: "tm.khaled-projects.net"
  TF_VAR_acm_validation_method: "DNS"
  TF_VAR_environment: "test"
  TF_VAR_route53_zone_id: "Z01106103VTZ4ZOEEI6L"
  TF_VAR_vpc_name: "ecs-vpc2"
  TF_VAR_public_subnet_1_name: "ecs-public-subnet-1"
  TF_VAR_public_subnet_2_name: "ecs-public-subnet-2"
  TF_VAR_igw_name: "ecs-igw"
  TF_VAR_public_route_table_name: "ecs-public-aws_route_table"
  TF_VAR_public_route_cidr: "0.0.0.0/0"
  TF_VAR_image_tag: "bc433161"


jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::540321526518:role/github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform apply
        run: terraform apply -auto-approve -input=false